// src/features/consejos/index.ts
export { ConsejoNacionalSection } from "./components/ConsejoNacionalSection"
export { ConsejoManagement } from "./components/ConsejoManagement"
export { ConsejoFormDialog } from "./components/ConsejoFormDialog"
export { MiembroFormDialog } from "./components/MiembroFormDialog"
export { ConsejoCard } from "./components/ConsejoCard"
export { ConsejeroDialog } from "./components/ConsejeroDialog"
export { HistorialConsejos } from "./components/HistorialConsejos"
export { ConsejoSkeleton } from "./components/ConsejoSkeleton"
export { useConsejoActual, useConsejosHistoricos } from "./hook/use-consejos"
export { useConsejoForm, useMiembroForm } from "./hook/use-consejo-form"
export type { ConsejoNacional, MiembroConsejo, ConsejoFormData, MiembroFormData } from "./model/types"